server:
  port: 8001

spring:
  application:
    name: roses-auth
  profiles:
    active: @spring.active@

auth:
  default-pwd: 123456 #重置密码的默认密码
mybatis-plus:
  typeAliasesPackage: com.stylefeng.roses.auth.modular.entity

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

log:
  path: /opt/logs/roses-auth

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

log:
  path: /opt/logs/roses-auth

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

---

spring:
  profiles: master
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/roses_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

log:
  path: /opt/logs/roses-auth

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
