server:
  port: 8000

jwt:
  header: Authorization           #http请求头所需要的字段
  secret: mySecret                #jwt秘钥
  expiration: 604800              #7天 单位:秒
  auth-path: /authService/login   #认证请求的路径

develop:
  open: false
  user-id: 1

roses:
  sign:
    time: 600 #签名默认失效时间 600秒

log:
  path: /opt/logs/roses-gateway

spring:
  application:
    name: roses-gateway

zuul:
  add-host-header: true
  routes:
    roses-auth: /roses-auth/**
    roses-message-service: /roses-message-service/**
    roses-account: /roses-account/**
    roses-order: /roses-order/**
    api-gate:
      path: /authService/**
      url: forward:/authService  #以/authService开头的请求转发到本网关的控制器
  retryable: false         #转发重试关闭

feign:
  hystrix:
    enabled: true

ribbon:
  connect-imeout: 300     #创建连接的超时时间 单位：毫秒
  read-timeout: 2000      #处理请求的超时时间 单位：毫秒
  max-auto-retries-next-server: 0 #切换实例的重试次数
  max-auto-retries: 0     #对当前实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000   #hystrix线程超过3秒熔断，数值大于ribbon的处理超时时间，留给ribbon重试，否则直接熔断，重试就没有意义了

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间
